ESP32_BASEADDR = 0x00310000

SETUP_INFO_OFFSET = 0
PASSWORD_LENGTH_OFFSET = 1
USER_PASSWORD_OFFSET = 2

SETUP_INFO_ADDR = ESP32_BASEADDR + SETUP_INFO_OFFSET
PASSWORD_LENGTH_ADDR = ESP32_BASEADDR + PASSWORD_LENGTH_OFFSET 
USER_PASSWORD_ADDR = ESP32_BASEADDR + USER_PASSWORD_OFFSET